project_id = "bpa-tool"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = []
enable_anonymous_sign_ins = true

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email]
enable_confirmations = true
max_frequency = "1m"
otp_length = 8

[functions.admin-password-verify]
verify_jwt = false
