begin;

alter table public.companies
  add column if not exists default_ai_provider text
  check (default_ai_provider in ('gemini', 'chatgpt', 'claude'));

create table if not exists public.company_ai_credentials (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  provider text not null check (provider in ('gemini', 'chatgpt', 'claude')),
  encrypted_key text not null,
  encryption_iv text not null,
  auth_tag text not null,
  key_last_four text,
  tested_model text,
  tested_at timestamptz,
  status text not null default 'active' check (status in ('active', 'disabled')),
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  unique (company_id, provider)
);

create index if not exists idx_company_ai_credentials_company
  on public.company_ai_credentials(company_id);

alter table public.company_ai_credentials enable row level security;

-- 암호문도 브라우저에 노출하지 않는다. 모든 접근은 권한 검사를 마친 백엔드만 수행한다.
revoke all on public.company_ai_credentials from anon, authenticated;
grant select, insert, update, delete on public.company_ai_credentials to service_role;
grant usage, select on all sequences in schema public to service_role;

commit;
