begin;

create table if not exists public.task_reports (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  project_id bigint not null references public.projects(id) on delete cascade,
  task_id bigint not null references public.tasks(id) on delete cascade,
  report_data jsonb not null check (jsonb_typeof(report_data) = 'object'),
  generated_by uuid references auth.users(id) on delete set null,
  generated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  unique (task_id)
);

create index if not exists idx_task_reports_company
  on public.task_reports (company_id, generated_at desc);

create index if not exists idx_task_reports_project
  on public.task_reports (project_id);

alter table public.task_reports enable row level security;

drop policy if exists task_reports_company_select on public.task_reports;
create policy task_reports_company_select on public.task_reports
for select to authenticated
using (
  exists (
    select 1 from public.projects p
    where p.id = task_reports.project_id
      and p.company_id = task_reports.company_id
      and public.is_active_company_member(p.company_id)
  )
);

drop policy if exists task_reports_company_insert on public.task_reports;
create policy task_reports_company_insert on public.task_reports
for insert to authenticated
with check (
  generated_by = auth.uid()
  and exists (
    select 1 from public.projects p
    join public.tasks t on t.project_id = p.id
    where p.id = task_reports.project_id
      and t.id = task_reports.task_id
      and p.company_id = task_reports.company_id
      and public.can_write_company(p.company_id)
  )
);

drop policy if exists task_reports_company_update on public.task_reports;
create policy task_reports_company_update on public.task_reports
for update to authenticated
using (
  exists (
    select 1 from public.projects p
    where p.id = task_reports.project_id
      and p.company_id = task_reports.company_id
      and public.can_write_company(p.company_id)
  )
)
with check (
  generated_by = auth.uid()
  and exists (
    select 1 from public.projects p
    join public.tasks t on t.project_id = p.id
    where p.id = task_reports.project_id
      and t.id = task_reports.task_id
      and p.company_id = task_reports.company_id
      and public.can_write_company(p.company_id)
  )
);

grant select, insert, update on public.task_reports to authenticated;
grant select, insert, update, delete on public.task_reports to service_role;
grant usage, select on sequence public.task_reports_id_seq to authenticated, service_role;

commit;
