begin;

create table if not exists public.companies (
  id bigint generated by default as identity primary key,
  name text not null unique,
  business_number text,
  status text not null default 'active' check (status in ('active', 'suspended')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text not null,
  app_role text not null default 'company_user' check (app_role in ('super_admin', 'company_user')),
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table if not exists public.company_memberships (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'company_editor' check (role in ('company_admin', 'company_editor', 'company_viewer')),
  status text not null default 'active' check (status in ('active', 'suspended')),
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  unique (company_id, user_id)
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  company_id bigint references public.companies(id) on delete set null,
  action text not null,
  target_type text not null,
  target_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

insert into public.companies (name)
select distinct trim(company_name)
from public.projects
where company_name is not null and trim(company_name) <> ''
on conflict (name) do nothing;

insert into public.companies (name)
select '미지정 협력사'
where exists (
  select 1 from public.projects
  where company_name is null or trim(company_name) = ''
)
on conflict (name) do nothing;

alter table public.projects add column if not exists company_id bigint references public.companies(id) on delete restrict;
alter table public.projects add column if not exists created_by_user_id uuid references auth.users(id) on delete set null;

update public.projects p
set company_id = c.id
from public.companies c
where p.company_id is null
  and c.name = coalesce(nullif(trim(p.company_name), ''), '미지정 협력사');

alter table public.projects alter column company_id set not null;

create index if not exists idx_projects_company on public.projects(company_id);
create index if not exists idx_company_memberships_user on public.company_memberships(user_id);
create index if not exists idx_company_memberships_company on public.company_memberships(company_id);
create index if not exists idx_audit_logs_company on public.audit_logs(company_id, created_at desc);

create or replace function public.is_super_admin(check_user uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where user_id = check_user and app_role = 'super_admin'
  );
$$;

create or replace function public.is_active_company_member(target_company_id bigint, check_user uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.company_memberships m
    join public.companies c on c.id = m.company_id
    where m.user_id = check_user
      and m.company_id = target_company_id
      and m.status = 'active'
      and c.status = 'active'
  );
$$;

create or replace function public.can_write_company(target_company_id bigint, check_user uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.company_memberships m
    join public.companies c on c.id = m.company_id
    where m.user_id = check_user
      and m.company_id = target_company_id
      and m.role in ('company_admin', 'company_editor')
      and m.status = 'active'
      and c.status = 'active'
  );
$$;

revoke all on function public.is_super_admin(uuid) from public;
revoke all on function public.is_active_company_member(bigint, uuid) from public;
revoke all on function public.can_write_company(bigint, uuid) from public;
grant execute on function public.is_super_admin(uuid) to authenticated, service_role;
grant execute on function public.is_active_company_member(bigint, uuid) to authenticated, service_role;
grant execute on function public.can_write_company(bigint, uuid) to authenticated, service_role;

alter table public.companies enable row level security;
alter table public.profiles enable row level security;
alter table public.company_memberships enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists companies_select on public.companies;
create policy companies_select on public.companies for select to authenticated
using (public.is_super_admin() or public.is_active_company_member(id));
drop policy if exists companies_admin_insert on public.companies;
create policy companies_admin_insert on public.companies for insert to authenticated
with check (public.is_super_admin());
drop policy if exists companies_admin_update on public.companies;
create policy companies_admin_update on public.companies for update to authenticated
using (public.is_super_admin()) with check (public.is_super_admin());

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select to authenticated
using (user_id = auth.uid() or public.is_super_admin());
drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update on public.profiles for update to authenticated
using (user_id = auth.uid()) with check (user_id = auth.uid() and app_role = 'company_user');

drop policy if exists memberships_select on public.company_memberships;
create policy memberships_select on public.company_memberships for select to authenticated
using (user_id = auth.uid() or public.is_super_admin());
drop policy if exists memberships_admin_update on public.company_memberships;
create policy memberships_admin_update on public.company_memberships for update to authenticated
using (public.is_super_admin()) with check (public.is_super_admin());

drop policy if exists audit_admin_select on public.audit_logs;
create policy audit_admin_select on public.audit_logs for select to authenticated
using (public.is_super_admin());

drop policy if exists projects_company_select on public.projects;
create policy projects_company_select on public.projects for select to authenticated
using (public.is_super_admin() or public.is_active_company_member(company_id));
drop policy if exists projects_company_insert on public.projects;
create policy projects_company_insert on public.projects for insert to authenticated
with check (public.can_write_company(company_id) and created_by_user_id = auth.uid());
drop policy if exists projects_company_update on public.projects;
create policy projects_company_update on public.projects for update to authenticated
using (public.can_write_company(company_id)) with check (public.can_write_company(company_id));
drop policy if exists projects_company_delete on public.projects;
create policy projects_company_delete on public.projects for delete to authenticated
using (public.can_write_company(company_id));

drop policy if exists tasks_company_select on public.tasks;
create policy tasks_company_select on public.tasks for select to authenticated
using (exists (select 1 from public.projects p where p.id = project_id and (public.is_super_admin() or public.is_active_company_member(p.company_id))));
drop policy if exists tasks_company_insert on public.tasks;
create policy tasks_company_insert on public.tasks for insert to authenticated
with check (exists (select 1 from public.projects p where p.id = project_id and public.can_write_company(p.company_id)));
drop policy if exists tasks_company_update on public.tasks;
create policy tasks_company_update on public.tasks for update to authenticated
using (exists (select 1 from public.projects p where p.id = project_id and public.can_write_company(p.company_id)));
drop policy if exists tasks_company_delete on public.tasks;
create policy tasks_company_delete on public.tasks for delete to authenticated
using (exists (select 1 from public.projects p where p.id = project_id and public.can_write_company(p.company_id)));

drop policy if exists domains_company_all on public.domains;
create policy domains_company_all on public.domains for all to authenticated
using (exists (select 1 from public.projects p where p.id = project_id and (public.is_super_admin() or public.is_active_company_member(p.company_id))))
with check (exists (select 1 from public.projects p where p.id = project_id and public.can_write_company(p.company_id)));

drop policy if exists interviews_company_all on public.interviews;
create policy interviews_company_all on public.interviews for all to authenticated
using (exists (select 1 from public.projects p where p.id = project_id and (public.is_super_admin() or public.is_active_company_member(p.company_id))))
with check (exists (select 1 from public.projects p where p.id = project_id and public.can_write_company(p.company_id)));

drop policy if exists processes_company_all on public.processes;
create policy processes_company_all on public.processes for all to authenticated
using (exists (select 1 from public.projects p where p.id = project_id and (public.is_super_admin() or public.is_active_company_member(p.company_id))))
with check (exists (select 1 from public.projects p where p.id = project_id and public.can_write_company(p.company_id)));

drop policy if exists bdw_tags_company_all on public.bdw_tags;
create policy bdw_tags_company_all on public.bdw_tags for all to authenticated
using (exists (
  select 1 from public.processes pr join public.projects p on p.id = pr.project_id
  where pr.id = process_id and (public.is_super_admin() or public.is_active_company_member(p.company_id))
))
with check (exists (
  select 1 from public.processes pr join public.projects p on p.id = pr.project_id
  where pr.id = process_id and public.can_write_company(p.company_id)
));

drop policy if exists ai_analysis_company_all on public.ai_analysis;
create policy ai_analysis_company_all on public.ai_analysis for all to authenticated
using (exists (select 1 from public.projects p where p.id = project_id and (public.is_super_admin() or public.is_active_company_member(p.company_id))))
with check (exists (select 1 from public.projects p where p.id = project_id and public.can_write_company(p.company_id)));

drop policy if exists to_be_company_all on public.to_be_processes;
create policy to_be_company_all on public.to_be_processes for all to authenticated
using (exists (select 1 from public.projects p where p.id = project_id and (public.is_super_admin() or public.is_active_company_member(p.company_id))))
with check (exists (select 1 from public.projects p where p.id = project_id and public.can_write_company(p.company_id)));

grant select, insert, update, delete on public.companies, public.profiles, public.company_memberships, public.audit_logs to authenticated;
grant select, insert, update, delete on public.projects, public.tasks, public.project_members, public.domains, public.interviews, public.processes, public.bdw_tags, public.ai_analysis, public.to_be_processes to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant select, insert, update, delete on public.companies, public.profiles, public.company_memberships, public.audit_logs to service_role;
grant usage, select on all sequences in schema public to service_role;

commit;
