begin;

create table if not exists public.company_user_accounts (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  auth_user_id uuid unique references auth.users(id) on delete set null,
  name text not null check (length(trim(name)) between 1 and 100),
  email text not null check (email = lower(trim(email))),
  last_access_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  unique (company_id, email)
);

create index if not exists idx_company_user_accounts_company
  on public.company_user_accounts(company_id, name);
create index if not exists idx_company_user_accounts_last_access
  on public.company_user_accounts(last_access_at desc nulls last);

insert into public.company_user_accounts (
  company_id,
  auth_user_id,
  name,
  email,
  last_access_at,
  created_at,
  updated_at
)
select
  membership.company_id,
  profile.user_id,
  profile.name,
  lower(trim(profile.email)),
  coalesce(profile.updated_at, membership.updated_at, profile.created_at),
  least(profile.created_at, membership.created_at),
  greatest(profile.updated_at, membership.updated_at)
from public.company_memberships membership
join public.profiles profile on profile.user_id = membership.user_id
where profile.app_role = 'company_user'
  and trim(profile.email) <> ''
on conflict (company_id, email) do update
set
  auth_user_id = excluded.auth_user_id,
  name = excluded.name,
  last_access_at = coalesce(
    public.company_user_accounts.last_access_at,
    excluded.last_access_at
  ),
  updated_at = now();

alter table public.company_user_accounts enable row level security;

revoke all on public.company_user_accounts from anon, authenticated;
grant select, insert, update, delete on public.company_user_accounts to service_role;
grant usage, select on sequence public.company_user_accounts_id_seq to service_role;

comment on table public.company_user_accounts is
  '관리자 선등록과 자유 가입을 함께 지원하는 협력사 사용자 디렉터리';
comment on column public.company_user_accounts.auth_user_id is
  '처음 로그인한 Supabase 익명 Auth 사용자와 연결되며 선등록 상태에서는 null';
comment on column public.company_user_accounts.last_access_at is
  '앱이 세션을 복원하고 /auth/me 조회에 성공한 최근 시간';

commit;
