begin;

create table if not exists public.panel_drafts (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  panel_key text not null check (panel_key in (
    'project_basic',
    'task_basic',
    'interview_answers',
    'process_editor',
    'report_frequency'
  )),
  scope_key text not null check (length(scope_key) between 1 and 200),
  project_id bigint references public.projects(id) on delete cascade,
  task_id bigint references public.tasks(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  saved_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  unique (company_id, user_id, panel_key, scope_key)
);

create index if not exists idx_panel_drafts_lookup
  on public.panel_drafts (company_id, user_id, panel_key, scope_key);
create index if not exists idx_panel_drafts_task
  on public.panel_drafts (task_id, updated_at desc nulls last);

alter table public.panel_drafts enable row level security;

drop policy if exists panel_drafts_select on public.panel_drafts;
create policy panel_drafts_select on public.panel_drafts for select to authenticated
  using (
    user_id = auth.uid()
    and public.is_active_company_member(company_id)
  );

drop policy if exists panel_drafts_insert on public.panel_drafts;
create policy panel_drafts_insert on public.panel_drafts for insert to authenticated
  with check (
    user_id = auth.uid()
    and public.can_write_company(company_id)
  );

drop policy if exists panel_drafts_update on public.panel_drafts;
create policy panel_drafts_update on public.panel_drafts for update to authenticated
  using (
    user_id = auth.uid()
    and public.can_write_company(company_id)
  )
  with check (
    user_id = auth.uid()
    and public.can_write_company(company_id)
  );

drop policy if exists panel_drafts_delete on public.panel_drafts;
create policy panel_drafts_delete on public.panel_drafts for delete to authenticated
  using (
    user_id = auth.uid()
    and public.can_write_company(company_id)
  );

revoke all on public.panel_drafts from anon;
grant select, insert, update, delete on public.panel_drafts to authenticated, service_role;
grant usage, select on sequence public.panel_drafts_id_seq to authenticated, service_role;

comment on table public.panel_drafts is
  '사용자 모드의 페이지별 수동 임시 저장 데이터. 정식 저장 완료 시 해당 scope 행을 삭제한다.';

commit;
