begin;

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  name text not null,
  company_name text,
  department_name text,
  description text,
  l1_domain text,
  analysis_goal text,
  analysis_period text,
  ai_engine text not null default 'chatgpt',
  start_date date,
  end_date date,
  participants jsonb not null default '[]'::jsonb,
  status text not null default 'active',
  created_by bigint,
  tenant_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  name text not null,
  l1 text not null,
  l2 text not null,
  l3 text not null,
  l4 text not null,
  goal text,
  start_date date,
  end_date date,
  participants jsonb not null default '[]'::jsonb,
  status text not null default 'registered',
  current_step integer not null default 1 check (current_step between 1 and 6),
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table if not exists public.project_members (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  user_id bigint not null,
  role text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.domains (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  parent_id bigint references public.domains(id) on delete cascade,
  level text not null check (level in ('L1','L2','L3','L4','L5','L6')),
  name text not null,
  description text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table if not exists public.interviews (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  domain_l3_id bigint references public.domains(id) on delete set null,
  interview_type text not null,
  text text,
  text_masked text,
  transcription text,
  transcription_masked text,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table if not exists public.processes (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  interview_id bigint references public.interviews(id) on delete cascade,
  task_id bigint references public.tasks(id) on delete cascade,
  level text not null check (level in ('L4','L5','L6')),
  name text not null,
  description text,
  execution_time integer,
  waiting_time numeric not null default 0,
  approval_waiting_time numeric not null default 0,
  method text,
  tool text,
  status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table if not exists public.bdw_tags (
  id bigint generated by default as identity primary key,
  process_id bigint not null references public.processes(id) on delete cascade,
  bdw_type text not null check (bdw_type in ('bottleneck','delay','waste','normal')),
  severity text not null default 'medium',
  created_at timestamptz not null default now()
);

create table if not exists public.ai_analysis (
  id bigint generated by default as identity primary key,
  process_id bigint not null references public.processes(id) on delete cascade,
  project_id bigint not null references public.projects(id) on delete cascade,
  name text not null,
  ai_possibility numeric not null,
  inefficiency numeric not null,
  fit_category text not null check (fit_category in ('A','B','C','D')),
  recommended_tech text,
  estimated_time_savings integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.to_be_processes (
  id bigint generated by default as identity primary key,
  original_process_id bigint not null references public.processes(id) on delete cascade,
  project_id bigint not null references public.projects(id) on delete cascade,
  name text not null,
  ai_applied boolean not null default false,
  original_execution_time integer,
  estimated_execution_time integer,
  automation_method text,
  created_at timestamptz not null default now()
);

create index if not exists idx_tasks_project on public.tasks(project_id);
create index if not exists idx_domains_project on public.domains(project_id);
create index if not exists idx_interviews_project on public.interviews(project_id);
create index if not exists idx_processes_project on public.processes(project_id);
create index if not exists idx_processes_task on public.processes(task_id);
create index if not exists idx_ai_analysis_project on public.ai_analysis(project_id);
create index if not exists idx_to_be_project on public.to_be_processes(project_id);

alter table public.projects enable row level security;
alter table public.tasks enable row level security;
alter table public.project_members enable row level security;
alter table public.domains enable row level security;
alter table public.interviews enable row level security;
alter table public.processes enable row level security;
alter table public.bdw_tags enable row level security;
alter table public.ai_analysis enable row level security;
alter table public.to_be_processes enable row level security;

grant select, insert, update, delete on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;

commit;
